<?php

namespace BviTemplateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdditionalServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTemplatesRepository extends EntityRepository {

    public function getEmailTemplateGridList($limit = 0, $offset = 10, $order_by = "id", $sort_order = "asc", $searchData, $SearchType, $objHelper) {
        $data = $this->trimSearchData($searchData, $SearchType);

        $query = $this->createQueryBuilder('a')
                ->where('a.status != :status')
                ->setParameter('status', 'Deleted');

        if ($SearchType == 'ORLIKE') {
            $likeStr = $objHelper->orLikeSearch($data);
        }
        if ($SearchType == 'ANDLIKE') {
            $likeStr = $objHelper->andLikeSearch($data);
        }

        if ($likeStr) {
            $query->andWhere($likeStr);
        }

        $query->orderBy($order_by, $sort_order);

        $countData = count($query->getQuery()->getArrayResult());

        $query->setMaxResults($limit);
        $query->setFirstResult($offset);

        $result = $query->getQuery()->getResult();

        $dataResult = array();

        if (count($result) > 0) {

            $dataResult['result'] = $result;
            $dataResult['totalRecord'] = $countData;

            return $dataResult;
        }
        return false;
    }
    
    public function trimSearchData($searchData, $SearchType) {

        $QueryStr = array();

        if (!empty($searchData)) {

            if ($SearchType == 'ANDLIKE') {

                $i = 0;
                foreach ($searchData as $key => $val) {
                    
                    if ($key == 'Key' && !empty($val)) {
                        
                        $QueryStr[$i]['Field'] = 'a.emailkey';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    if ($key == 'Subject' && !empty($val)) {
                        
                        $QueryStr[$i]['Field'] = 'a.subject';
                        $QueryStr[$i]['Value'] = $val;
                        $QueryStr[$i]['Operator'] = 'LIKE';
                    }
                    $i++;
                }
            } else {
//                !empty($searchData['Username']) ? $QueryStr['u.username'] = $searchData['Username'] : "";
//                !empty($searchData['Email']) ? $QueryStr['u.email'] = $searchData['Email'] : "";
            }
        }
        return $QueryStr;
    }

}
